rm(list = ls())
source("/ihme/cc_resources/libraries/current/r/get_draws.R")

typhi_locs <- c(6,
                7,
                8,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                22,
                23,
                24,
                25,
                26,
                27,
                28,
                29,
                30,
                139,
                140,
                141,
                142,
                143,
                144,
                145,
                146,
                147,
                148,
                149,
                150,
                151,
                152,
                153,
                154,
                155,
                156,
                157,
                160,
                161,
                162,
                163,
                164,
                165,
                168,
                169,
                170,
                171,
                172,
                173,
                175,
                176,
                177,
                178,
                179,
                180,
                181,
                182,
                183,
                184,
                185,
                186,
                187,
                189,
                190,
                191,
                198,
                200,
                201,
                202,
                203,
                204,
                205,
                206,
                207,
                208,
                209,
                210,
                211,
                212,
                213,
                214,
                215,
                216,
                217,
                218,
                298,
                320,
                351,
                369,
                374,
                376,
                380,
                413,
                416,
                435,
                522
)

#loop through and get incidence rate for all endemic locations
for(l in typhi_locs){
  df <- get_draws("cause_id", 319, 
                year_id=c(1990:2018), 
                source="como", status="best", 
                gbd_round_id=6, 
                decomp_step="step5", 
                age_group_id = 22, sex_id = 3, 
                location_id = l,
                measure_id = 6,
                metric_id = 3)
  
  if(l == typhi_locs[1]){
    typhi <- df
  }else{
    typhi <- rbind(typhi, df)
  }
}

saveRDS(typhi, '/ihme/homes/annieb6/AMR/typhi_paratyphi/GBD_numbers/Typhi_incidence_rate.rds')

# and for paratyphi
paratyphi_locs <- c(6,
                    7,
                    8,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    161,
                    162,
                    163,
                    164,
                    165,
                    183,
                    186,
                    298,
                    320,
                    351,
                    369,
                    374,
                    376,
                    380,
                    413,
                    416
)

for(l in paratyphi_locs){
  df <- get_draws("cause_id", 320, 
                  year_id=c(1990:2018), 
                  source="como", status="best", 
                  gbd_round_id=6, 
                  decomp_step="step5", 
                  age_group_id = 22, sex_id = 3, 
                  location_id = l,
                  measure_id = 6,
                  metric_id = 3)
  
  if(l == paratyphi_locs[1]){
    paratyphi <- df
  }else{
    paratyphi <- rbind(paratyphi, df)
  }
}

saveRDS(paratyphi, '/ihme/homes/annieb6/AMR/typhi_paratyphi/GBD_numbers/Paratyphi_incidence_rate.rds')
